FROM openjdk:18-ea-11-jdk-alpine
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
# ENV USE_PROFILE prod
# ENV KMS_HOST dangdang-kms
# ENTRYPOINT ["java","-Dspring.profiles.active=${USE_PROFILE}","-Dkms.url=ws://${KMS_HOST}:8888/kurento","-jar","/app.jar"]