import Head from "next/head";

export default function Layout({children}) {
  return <>
    <Head>
    <title>당당|당당하게 면접보자!</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>{children}</div>
  </>
}
